### ISSUE TITLE
Command failed: /bin/sh 1: ffmpeg: not found

### ISSUE THREAD

**Issue by zamarrong** [meatspaces/meatspace-chat-v2#97]
Hi, i installed succefully ffmpeg but i have this error:
error  { [Error: Command failed: /bin/sh: 1: ffmpeg: not found
] killed: false, code: 127, signal: null }

Where i need put /bin/sh folder?

**Comment by jasonrhodes** [comment]
Most likely the ffmpeg binary wasn't installed in your $PATH, do you know where it was installed? Good place to start.

**Comment by zamarrong** [comment]
Yes it is installed in my ubuntu user folder

**Comment by bennlich** [comment]
@zamarrong: In `~/.profile` try adding `export PATH="$PATH:$HOME/bin` (assuming ffmpeg was installed to ~/bin).

You need to be able to run `ffmpeg` from your command prompt. You know you did it right if running `which ffmpeg` prints out the path to your installation of ffmpeg.

**Comment by TheAlphaNerd** [comment]
closing
